#!/usr/bin/env bash
#
# Core apply. Near-empty on purpose: core marks the phase boundary.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

# A generated shim, not a symlink: through a symlink BASH_SOURCE would point at
# ~/.local/bin and bin/dot would look for lib/ there. core/doctor.sh and
# uninstall.sh grep -F the DOT_ROOT line below to recognise it as ours.
bin_dir="$HOME/.local/bin"
target="$bin_dir/dot"

if [[ $DOT_DRY_RUN == 1 ]]; then
  info "write   ~/.local/bin/dot"
else
  mkdir -p "$bin_dir"
  cat >"$target" <<EOF
#!/usr/bin/env bash
# Generated by core/apply.sh. Points at the repo you installed from.
export DOT_ROOT="$DOT_ROOT"
exec "\$DOT_ROOT/bin/dot" "\$@"
EOF
  chmod +x "$target"
  ok "dot is at ~/.local/bin/dot"
fi

if [[ $DOT_DRY_RUN != 1 ]]; then
  mkdir -p "$DOT_CONFIG_HOME" "$DOT_STATE_HOME" "$HOME/.local/share"
fi
