#!/usr/bin/env bash
#
# Core apply. Deliberately almost empty -- core exists to make the phase
# boundary visible in the tree, not to accumulate special cases.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

# Put `dot` on PATH, as a generated shim rather than a symlink.
#
# A symlink looks tidier but breaks the CLI: bash sets BASH_SOURCE to the
# symlink's own path, so bin/dot would look for lib/ next to ~/.local/bin and
# find nothing. Resolving that needs a readlink loop inside bin/dot, a second
# copy of the one in lib/dot.sh that then has to stay in sync. The shim
# sidesteps it by exporting DOT_ROOT and exec'ing the real path, so exactly one
# place knows where the repo is and every hook inherits it.
#
# Generated rather than tracked in core/home/ because its content depends on
# where you cloned the repo.
bin_dir="$HOME/.local/bin"
target="$bin_dir/dot"

if [[ $DOT_DRY_RUN == 1 ]]; then
  info "write   ~/.local/bin/dot"
else
  mkdir -p "$bin_dir"
  cat >"$target" <<EOF
#!/usr/bin/env bash
# Generated by core/apply.sh. Points at the repo you installed from.
export DOT_ROOT="$DOT_ROOT"
exec "\$DOT_ROOT/bin/dot" "\$@"
EOF
  chmod +x "$target"
  ok "dot is at ~/.local/bin/dot"
fi

# XDG directories, so modules can assume they exist.
if [[ $DOT_DRY_RUN != 1 ]]; then
  mkdir -p "$DOT_CONFIG_HOME" "$DOT_STATE_HOME" "$HOME/.local/share"
fi
