#!/usr/bin/env bash
#
# Generate ~/.config/git/config.local from the user config.
#
# This is the shape every "templated" file in this repo should take: read a
# few values, printf them into a real file that the tool's own include
# mechanism picks up. No template engine, no .tmpl extension, no rendering
# pass. If a generator here ever needs a conditional, that conditional belongs
# in git's config language instead.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

name=$(cfg_get 'user.name')
email=$(cfg_get 'user.email')
signingkey=$(module_setting git signingkey '')

dest="$HOME/.config/git/config.local"

if [[ -z $name || -z $email ]]; then
  warn 'user.name or user.email is empty in config.toml -- skipping config.local'
  exit 0
fi

if [[ $DOT_DRY_RUN == 1 ]]; then
  info "write   ~/.config/git/config.local"
  exit 0
fi

mkdir -p "$(dirname "$dest")"
{
  printf '# Generated by the git module. Edits here are overwritten.\n'
  printf '# Change the values in ~/.config/dotfiles/config.toml instead.\n\n'
  printf '[user]\n\tname = %s\n\temail = %s\n' "$name" "$email"
  if [[ -n $signingkey ]]; then
    printf '\tsigningkey = %s\n\n' "$signingkey"
    printf '[gpg]\n\tformat = ssh\n\n'
    printf '[commit]\n\tgpgsign = true\n'
  fi
} >"$dest"

ok "git identity: $name <$email>"
