#!/usr/bin/env bash
#
# Generate ~/.config/git/config.local: a few values printf'd into a file git's
# own include mechanism reads. No template engine. A conditional belongs in
# git's config language, not here.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

name=$(cfg_get 'user.name')
email=$(cfg_get 'user.email')
signingkey=$(module_setting git signingkey '')

dest="$HOME/.config/git/config.local"

# The ssh module does NOT cover signing: git shells out to gpg.ssh.program,
# which defaults to `ssh-keygen -Y sign`, and ssh-keygen never reads
# ~/.ssh/config. Only 1Password's own signer reaches the vault.
opsign=${DOT_OP_SSH_SIGN:-/Applications/1Password.app/Contents/MacOS/op-ssh-sign}

# Absolute, because git run from a GUI inherits no shell PATH. Only written
# when VS Code is installed (the apps module), or every commit would fail on a
# missing editor.
code=${DOT_CODE_BIN:-/opt/homebrew/bin/code}

if [[ -z $name || -z $email ]]; then
  warn 'user.name or user.email is empty in config.toml -- skipping config.local'
  exit 0
fi

if [[ $DOT_DRY_RUN == 1 ]]; then
  info "write   ~/.config/git/config.local"
  exit 0
fi

# Decided out here: `warn` goes to stderr, but inside the generator below
# stdout IS config.local. All three signing keys or none: `gpgsign = true`
# with no reachable signer aborts every commit.
sign=0
if [[ -n $signingkey ]]; then
  if [[ -x $opsign ]]; then
    sign=1
  else
    warn 'commit signing off -- 1Password is not installed yet; re-run `dot apply`'
  fi
fi

# git's config language: `#` and `;` start a comment and a bare `"` is
# stripped, silently. Inside quotes only `"` and `\` need escaping.
q() {
  local v=$1
  v=${v//\\/\\\\}
  v=${v//\"/\\\"}
  printf '"%s"' "$v"
}

mkdir -p "$(dirname "$dest")"
{
  printf '# Generated by the git module. Edits here are overwritten.\n'
  printf '# Change the values in ~/.config/dotfiles/config.toml instead.\n\n'
  printf '[user]\n\tname = %s\n\temail = %s\n' "$(q "$name")" "$(q "$email")"
  if ((sign)); then
    printf '\tsigningkey = %s\n\n' "$(q "$signingkey")"
    printf '[gpg]\n\tformat = ssh\n\n'
    printf '[gpg "ssh"]\n\tprogram = %s\n\n' "$(q "$opsign")"
    printf '[commit]\n\tgpgsign = true\n'
  fi
  if [[ -x $code ]]; then
    printf '\n[core]\n\teditor = %s\n' "$(q "$code --wait")"
  fi
} >"$dest"

ok "git identity: $name <$email>"
