#!/usr/bin/env bash
#
# config.local is written, not linked, so the symlink sweep cannot see it.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

dest="$HOME/.config/git/config.local"

# The header is the proof of ownership: config.local is a conventional name,
# and a hand-written one may predate the module.
if [[ -f $dest ]] && grep -q 'Generated by the git module' "$dest"; then
  fs_discard "$dest"
elif [[ -e $dest ]]; then
  warn 'left alone  ~/.config/git/config.local (not generated by this repo)'
fi
