#!/usr/bin/env bash
#
# Remove the file apply.sh generates.
#
# ~/.config/git/config.local is written, not linked -- its contents come from
# your config.toml -- so it is invisible to the symlink sweep in uninstall.sh
# and has to be named here. The tracked half of this module, home/.config/git/,
# is linked and needs no hook.

set -euo pipefail
source "${DOT_ROOT:?}/lib/dot.sh"

dest="$HOME/.config/git/config.local"

# The header apply.sh writes is the proof of ownership, and checking it is not
# paranoia: config.local is the conventional name for "the git config I keep
# off GitHub", so there is a real chance the file at this path predates the
# module and was written by hand.
if [[ -f $dest ]] && grep -q 'Generated by the git module' "$dest"; then
  fs_discard "$dest"
elif [[ -e $dest ]]; then
  warn 'left alone  ~/.config/git/config.local (not generated by this repo)'
fi
